# Generated by Django 3.2.5 on 2021-07-14 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ref', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentinstance',
            name='environments',
            field=models.ManyToManyField(blank=True, related_name='component_instances', to='ref.Environment', verbose_name='environnements '),
        ),
        migrations.AlterField(
            model_name='environment',
            name='show_sensitive_data',
            field=models.NullBooleanField(choices=[(None, 'défini par la typologie'), (False, 'cacher'), (True, 'montrer')], verbose_name='afficher les informations sensibles'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='typology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ref.environmenttype', verbose_name='typologie'),
        ),
        migrations.AlterField(
            model_name='implementationfielddescription',
            name='datatype',
            field=models.CharField(choices=[('str', 'chaîne de caractères'), ('int', 'entier'), ('bool', 'booléen')], default='str', max_length=20, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='mageparam',
            name='app',
            field=models.CharField(choices=[('ref', 'ref'), ('scm', 'scm')], max_length=5, verbose_name='application'),
        ),
    ]
