# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-13 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ref', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentinstance',
            name='environments',
            field=models.ManyToManyField(blank=True, related_name='component_instances', to='ref.Environment', verbose_name=b'environnements '),
        ),
        migrations.AlterField(
            model_name='environment',
            name='show_sensitive_data',
            field=models.NullBooleanField(choices=[(None, 'd\xe9fini par la typologie'), (False, b'cacher'), (True, b'montrer')], verbose_name=b'afficher les informations sensibles'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='typology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ref.EnvironmentType', verbose_name='typologie'),
        ),
        migrations.AlterField(
            model_name='implementationfielddescription',
            name='datatype',
            field=models.CharField(choices=[(b'str', b'cha\xc3\xaene de caract\xc3\xa8res'), (b'int', b'entier'), (b'bool', b'bool\xc3\xa9en')], default=b'str', max_length=20, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='mageparam',
            name='app',
            field=models.CharField(choices=[(b'ref', b'ref'), (b'scm', b'scm')], max_length=5, verbose_name='application'),
        ),
    ]
