# Generated by Django 3.2.12 on 2022-10-01 11:44

from django.db import migrations


def forward(apps, schema_editor):
    Project = apps.get_model('ref', 'Project')
    default_project = Project.objects.first() or Project.objects.get_or_create(name='MIGRATED_PROJECT', defaults={'description': "Created by database upgrade. Rename it as you wish"})[0]
    default_project.save()

    Environment = apps.get_model('ref', 'Environment')
    for envt in Environment.objects.all():
        if not envt.project:
            envt.project = default_project
            envt.save()

    Application = apps.get_model('ref', 'Application')
    for app in Application.objects.all():
        if not app.project:
            app.project = default_project
            app.save()


class Migration(migrations.Migration):
    """ Create data for foreign keys that become compulsory in next migration """
    dependencies = [
        ('ref', '0003_alter_environment_show_sensitive_data'),
    ]

    operations = [
        migrations.RunPython(forward),
    ]
