# Generated by Django 3.2.15 on 2022-10-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ref', '0006_auto_20221001_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('name', 'project'), name='application_uniqueness'),
        ),
    ]
