# Generated by Django 3.2.15 on 2022-10-02 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ref', '0007_auto_20221001_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentinstance',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='component_instances', to='ref.project', verbose_name='project'),
        ),
    ]
