# Generated by Django 3.2.15 on 2022-10-02 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ref', '0009_auto_20221002_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentinstance',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_instances', to='ref.project', verbose_name='project'),
        ),
    ]
