# Generated by Django 3.2.15 on 2022-10-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ref', '0010_alter_componentinstance_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentinstancefield',
            name='value',
            field=models.CharField(db_index=True, max_length=512, verbose_name='valeur'),
        ),
    ]
