# Generated by Django 3.2.16 on 2022-12-12 15:08

from django.db import migrations, models

def forward(apps, schema_editor):
    ComponentInstance = apps.get_model('ref', 'ComponentInstance')
    for ci in ComponentInstance.objects.all():
        if not ci.stable_key:
            ci.stable_key = ci.pk

            ci.save()

class Migration(migrations.Migration):

    dependencies = [
        ('ref', '0011_alter_componentinstancefield_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentinstance',
            name='stable_key',
            field=models.IntegerField(null=True, verbose_name='only used in specific serialization scenarii'),
        ),
        migrations.AlterField(
            model_name='implementationdescription',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='implementationrelationtype',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='type relation'),
        ),
        migrations.RunPython(forward),
    ]
