# Generated by Django 3.2.9 on 2021-11-13 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='installableset',
            options={'permissions': (('validate_installableset', 'can change the status of the set'), ('install_installableset', 'can reference an installation')), 'verbose_name': 'élément à installer', 'verbose_name_plural': 'éléments à installer'},
        ),
    ]
