# Generated by Django 3.2.12 on 2022-10-01 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ref', '0005_auto_20221001_1356'),
        ('scm', '0002_alter_installableset_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='installableset',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ref.project'),
        ),
    ]
