# Generated by Django 3.2.12 on 2022-10-01 12:10

from django.db import migrations

def forward(apps, schema_editor):
    """Tries to set the right project, otherwise default - in all cases there should only be zero to one projects when using this migration"""
    Project = apps.get_model('ref', 'Project')
    default_project = Project.objects.first() or Project.objects.get_or_create(name='MIGRATED_PROJECT', defaults={'description': "Created by database upgrade. Rename it as you wish"})[0]
    default_project.save()

    Delivery = apps.get_model('scm', 'Delivery')
    for iset in Delivery.objects.all():
        if not iset.project:
            if iset.set_content:
                iset.project = iset.set_content.all()[0].what_is_installed.logical_component.application.project
            else:
                iset.project = default_project
            iset.save()

    BackupSet = apps.get_model('scm', 'BackupSet')
    for iset in BackupSet.objects.all():
        if not iset.project:
            iset.project = default_project
            iset.save()


class Migration(migrations.Migration):
    """prepares making InstallableSet.project compulsory"""

    dependencies = [
        ('scm', '0003_installableset_project'),
        ('ref', '0005_auto_20221001_1356'),
    ]

    operations = [
        migrations.RunPython(forward),
    ]
