# Generated by Django 3.2.12 on 2022-10-01 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ref', '0005_auto_20221001_1356'),
        ('scm', '0004_auto_20221001_1410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backupset',
            options={'verbose_name': 'sauvegarde', 'verbose_name_plural': 'sauvegarde'},
        ),
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': "package d'installation", 'verbose_name_plural': "packages d'installation"},
        ),
        migrations.AlterField(
            model_name='installableset',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ref.project'),
        ),
    ]
