# Generated by Django 3.2.16 on 2022-12-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0006_auto_20221001_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installationmethod',
            name='name',
            field=models.CharField(max_length=254, unique=True, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='packagechecker',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Python checker class name'),
        ),
    ]
