version: '3.3'

services:
  mage:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: mage:latest
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
    depends_on:
      - postgres
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=mage
      - POSTGRES_PASSWORD=mage_password
      - POSTGRES_DB=mage

volumes:
  postgres_data: